### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [cornetth/franklin-w-dixon_the-tower-treasure#1]
- [ ] Re "REWARD" in ch. 10, we almost never want all-caps in the text (see [SEMoS 8.3.3](https://standardebooks.org/manual/1.7.0/single-page#8.3.3)). The text should be titlecased and adjusted via CSS.
- [ ] The text on the sign should also be in a blockquote, i.e. "The above reward will be paid…"
- [ ] The sign is not bolded in the scans, so does not need to be here, either.
- [ ] "The End" should be removed from the last chapter; we don't keep those.
- [ ] There are references to a number of publications (Oliver Twist, Merchant of Venice, etc.); these should be italicized and tagged appropriately rather than quoted; see [SEMoS 8.2.11.2](https://standardebooks.org/manual/1.7.0/single-page#8.2.11.2). This includes the name of the next Hardy Boys book in the last chapter.
- [ ] We don't change "worth while," so that will need to be backed out of the a1c318105 commit. In general, we don't mess with compound words at all beyond what `modernize-spelling` does; the possible changes are too many, most of them are judgment calls ("some day" is used almost as much as "someday", e.g.), and they're inconsistently applied since they're not part of our tools.
- [ ] I think the "teek-tock" in ch. 15 would qualify as a "sound," and thus fall under [SEMoS 8.2.6](https://standardebooks.org/manual/1.7.0/single-page#8.2.6). (Replacing the quotes.) Same for the "ticktock" that follows.
- [ ] There are quite a number of "dad"s that are used as proper nouns and therefore should be capitalized. Since it's changing the text it would be an `[Editorial]` commit.
